### Muestra todos los productos con un limite
GET http://localhost:8080/api/products?limit=5

### Muestra un producto por id
GET http://localhost:8080/api/products/1

### Agrega un producto
POST http://localhost:8080/api/products/
content-type: application/json

{
    "title": "Producto",
    "description": "Descripcion del producto",
    "code": "P1",
    "price": 1000,
    "category": "Category 1",
    "thumbnails": [ "url1", "url2" ],
    "stock": 10
}

### Actualiza un producto
PUT http://localhost:8080/api/products/1
content-type: application/json

{
    "stock": 0,
    "status": false
}

### Elimina un producto
DELETE http://localhost:8080/api/products/3


