### Carritos
GET http://localhost:8080/api/carts

### Carrito por Id
GET http://localhost:8080/api/carts/653988263bf23eeb2d76748c

### Crear carrito
POST http://localhost:8080/api/carts

### Agrega un producto al carrito
PUT http://localhost:8080/api/carts/65398889a956a34bac4f36bc/products/64fc8ad5cf7383d11afde544
content-type: application/json

### Elimina un producto del carrito
DELETE http://localhost:8080/api/carts/65398889a956a34bac4f36bc/products/64fc8ad5cf7383d11afde544

### Finaliza la compra
GET http://localhost:8080/api/carts/65398889a956a34bac4f36bc/purcharse

### Elimina carrito
DELETE http://localhost:8080/api/carts/65398889a956a34bac4f36bc