### Carritos
GET http://localhost:8080/api/carts

### Carrito por id
GET http://localhost:8080/api/carts/659ab014e9991bfce804c39f

### Crear carrito
POST http://localhost:8080/api/carts

### Agrega un producto al carrito
PUT http://localhost:8080/api/carts/659ab014e9991bfce804c39f/products/64fc8ac6cf7383d11afde542

### Elimina un producto del carrito
DELETE http://localhost:8080/api/carts/659ab014e9991bfce804c39f/products/64fc8ac6cf7383d11afde542

### Finaliza la compra
GET http://localhost:8080/api/carts/659ab014e9991bfce804c39f/purcharse

### Elimina carrito
DELETE http://localhost:8080/api/carts/65398889a956a34bac4f36bc