### Carritos
GET http://localhost:8080/api/carts

### Carrito por ID
GET http://localhost:8080/api/carts/6531691ca9e65cb117e6bf04

### Agrega carrito
POST http://localhost:8080/api/carts

### Agrega un producto al carrito
PUT http://localhost:8080/api/carts/6531691ca9e65cb117e6bf04
content-type: application/json

{
    "product": "64fc8ad5cf7383d11afde544"
}

### Elimina un producto del carrito
DELETE http://localhost:8080/api/carts/6531691ca9e65cb117e6bf04/products/64fc8ad5cf7383d11afde544

### Elimina carrito
DELETE http://localhost:8080/api/carts/6531691ca9e65cb117e6bf04