### Envia un email para restablecer la contraseña
POST http://localhost:8080/api/sessions/forgot-password
content-type: application/json

{
    "email": "irma@email.com"
}

### Verifica el token
GET http://localhost:8080/api/sessions/reset-password/65393c490ea8b0ad0b7e5728/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlybWFAZW1haWwuY29tIiwiaWQiOiI2NTM5M2M0OTBlYThiMGFkMGI3ZTU3MjgiLCJpYXQiOjE3MDA2NjQwMDAsImV4cCI6MTcwMDY2NzYwMH0.BCYJYtI3265YIYS8JeK3XHkxV3voA-RsfW1c1zCl5dE

### Recupera la contraseña
POST http://localhost:8080/api/sessions/reset-password/65393c490ea8b0ad0b7e5728/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlybWFAZW1haWwuY29tIiwiaWQiOiI2NTM5M2M0OTBlYThiMGFkMGI3ZTU3MjgiLCJpYXQiOjE3MDExOTMyMDUsImV4cCI6MTcwMTE5NjgwNX0.CDr8QWfM1tT9HamksufcypvaktXKGlh1FHBwD7x00Uo
content-type: application/json

{
    "password": "1234567"
}

