### Envia un email para restablecer la contraseña
POST http://localhost:8080/api/sessions/forgot-password
content-type: application/json

{
    "email": "josemorales270102@gmail.com"
}

### Verifica el token
GET http://localhost:8080/api/sessions/reset-password/65393c490ea8b0ad0b7e5728/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlybWFAZW1haWwuY29tIiwiaWQiOiI2NTM5M2M0OTBlYThiMGFkMGI3ZTU3MjgiLCJpYXQiOjE3MDMyNzc1MTQsImV4cCI6MTcwMzI4MTExNH0.hXr1IKS9Prk1mk5bAn8WdZr66UHYcO3ZoZ6LZSh2k4M

### Recupera la contraseña
POST http://localhost:8080/api/sessions/reset-password/656609e7446fc14435e4fa5f/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2Vtb3JhbGVzMjcwMTAyQGdtYWlsLmNvbSIsImlkIjoiNjU2NjA5ZTc0NDZmYzE0NDM1ZTRmYTVmIiwiaWF0IjoxNzAzMjc3NzEzLCJleHAiOjE3MDMyODEzMTN9.IcRRcruhSqaLVYWUKMBOoQ5Tqa_zirvUJ747Z4V3A0s
content-type: application/json

{
    "password": "123456"
}

