### Envia un email para restablecer la contraseña
POST http://localhost:8080/api/users/forgot-password
content-type: application/json

{
    "email": "irma@email.com"
}

### Verifica el token
GET http://localhost:8080/api/users/reset-password/65393c490ea8b0ad0b7e5728/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlybWFAZW1haWwuY29tIiwiaWQiOiI2NTM5M2M0OTBlYThiMGFkMGI3ZTU3MjgiLCJpYXQiOjE3MDA2MDkzNTksImV4cCI6MTcwMDYxMjk1OX0.oPhdFl2iQA6IRgSM_w_x3k4MUq0e7OS8F5LFEceem9I

### Recupera la contraseña
POST http://localhost:8080/api/users/reset-password/65393c490ea8b0ad0b7e5728/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlybWFAZW1haWwuY29tIiwiaWQiOiI2NTM5M2M0OTBlYThiMGFkMGI3ZTU3MjgiLCJpYXQiOjE3MDA2MDkzNTksImV4cCI6MTcwMDYxMjk1OX0.oPhdFl2iQA6IRgSM_w_x3k4MUq0e7OS8F5LFEceem9I
content-type: application/json

{
    "password": "abc123"
}

