### Listado de productos
GET http://localhost:8080/api/products

### Listado de productos con parametros
GET http://localhost:8080/api/products?page=1&limit=2&category=camisas&sort=desc

### Producto por id
GET http://localhost:8080/api/products/64fc8a54cf7383d11afde53d

### Nuevo producto
POST http://localhost:8080/api/products
content-type: application/json

{
    "title": "Nuevo Producto Premium",
    "description": "Descripcion del producto",
    "code": "P1",
    "price": 4000,
    "image": "https://images.pexels.com/photos/1043148/pexels-photo-1043148.jpeg?auto=compress&cs=tinysrgb&w=1600",
    "category": "Remeras",
    "stock": 2    
}

### Actualiza producto
PUT http://localhost:8080/api/products/6539846c266e6b6600c0f114
content-type: application/json

{
    "stock": 0,
    "status": false
}

### Elimina producto
DELETE http://localhost:8080/api/products/657728839d122dceeb0b26a3


