### Usuarios
GET http://localhost:8080/api/users

### Usuario por id
GET http://localhost:8080/api/users/65393c1b0ea8b0ad0b7e5723

### Agregar usuario
POST http://localhost:8080/api/users/register
content-type: application/json

{
    "firstName": "Irma",
    "lastName": "Arias",
    "email": "irma2@email.com",
    "age": 70,
    "password": "123456"
}

### Eliminar Usuario
DELETE http://localhost:8080/api/users/653983df266e6b6600c0f10c

