### Usuarios
GET http://localhost:8080/api/users

### Nuevo Usuario
POST http://localhost:8080/api/users/register
content-type: application/json

{
    "firstName": "Irma",
    "lastName": "Arias",
    "email": "irma@email.com",
    "age": 79,
    "password": "123456"
}

### Eliminar Usuario
DELETE http://localhost:8080/api/users/651c6b2fa27467b76b91874d

### Login
POST http://localhost:8080/api/users/login
content-type: application/json

{
    "email": "irma@email.com",
    "password": "123456"
}
